{
  imports = [
    ./hardware-configuration.nix
    ./modules/desktop.nix
    ./modules/flatpak.nix
    ./modules/gaming.nix
    ./modules/glance.nix
    ./modules/keepassxc.nix
    ./modules/neovim.nix
    ./modules/networking.nix
    ./modules/nixflix.nix
    ./modules/nvidia.nix
    ./modules/packages.nix
    ./modules/rclone.nix
    ./modules/reel.nix
    ./modules/secrets.nix
    ./modules/shell.nix
    ./modules/spicetify.nix
    ./modules/syncthing.nix
    ./modules/system.nix
  ];
}
